### PR TITLE
Docs testing orig externals

### PR DESCRIPTION
**Pull request by phobson**
Removing the SVN stuff made the diff in https://github.com/hetland/pygridgen/pull/8 too unwieldy. 

This is a cleaner version of the PR:
 + cleaned up CSA with how it loads the extension (and trailing removed whitespace)
 + clean up `assert` statements
 + removed `print` statements
 + added basic units tests, Travis CI
 + added Mac OS X and Linux install documentation
 + lastly, downgraded `external/gridutils` to the version in `octant` (everything else is actually more up-to-date than octant according to changelogs)

I can scrape out the SVN files after this is ready.

### CODE REVIEW

**Comment by phobson** [comment]
@hetland Hold off on merging this for a bit. The diff between gridutils v0.43 (from octant) and what was v0.51 (original in pygridgen) is not that big.

I like to track down where the regression is and try to fix it. I'll let you know when I give up or figure it out.

**Comment by hetland** [comment]
OK, this is a good time to hold off, as I've got other stuff to do at the
moment. Let me know when you think it's ready.

On Wed, Jan 7, 2015 at 1:10 PM, Paul Hobson <notifications@github.com>
wrote:

> @hetland <https://github.com/hetland> Hold off on merging this for a bit.
> The diff between gridutils v0.43 (from octant) and what was v0.51 (original
> in pygridgen) is not that big.
>
> I like to track down where the regression is and try to fix it. I'll let
> you know when I give up or figure it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hetland/pygridgen/pull/9#issuecomment-69073878>.
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by phobson** [comment]
OK -- I think this is as ready as it's going to get for now. I tried emailing Dr. Sakov about why `gridutils` v0.51 wasn't playing nice, but he said he hadn't dealt with any of those codes for so long that he didn't really have much to say. It's probably just a missing `include <...>` statement or something -- but my C-programming ain't so good. 

This version builds on travis-ci.org, runs tests, and has `nn`, `csa`, and `gridgen` source from the latest available on Google Code.

**Comment by phobson** [comment]
Thanks for merging @hetland ! 

Now if you go to travis-ci.org, you should be able to log in with your github account and give their build bots permission to listen to this repository.

**Pull request merged**
